/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EngineerRouteImport } from './routes/engineer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CustomerJobsRouteImport } from './routes/customer/jobs'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardDispatchRouteImport } from './routes/dashboard/dispatch'
import { Route as DashboardEngineersRouteImport } from './routes/dashboard/engineers'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard/invoices'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as EngineerJobsRouteImport } from './routes/engineer/jobs'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRoute = EngineerRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerJobsRoute = CustomerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CustomerRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDispatchRoute = DashboardDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEngineersRoute = DashboardEngineersRouteImport.update({
  id: '/engineers',
  path: '/engineers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const EngineerJobsRoute = EngineerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => EngineerRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/engineer': typeof EngineerRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/customer/jobs': typeof CustomerJobsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/dispatch': typeof DashboardDispatchRoute
  '/dashboard/engineers': typeof DashboardEngineersRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/engineer/jobs': typeof EngineerJobsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/engineer': typeof EngineerRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/customer/jobs': typeof CustomerJobsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/dispatch': typeof DashboardDispatchRoute
  '/dashboard/engineers': typeof DashboardEngineersRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/engineer/jobs': typeof EngineerJobsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/engineer': typeof EngineerRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/customer/jobs': typeof CustomerJobsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/dispatch': typeof DashboardDispatchRoute
  '/dashboard/engineers': typeof DashboardEngineersRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/engineer/jobs': typeof EngineerJobsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/dashboard'
    | '/engineer'
    | '/login'
    | '/signup'
    | '/customer/jobs'
    | '/dashboard/customers'
    | '/dashboard/dispatch'
    | '/dashboard/engineers'
    | '/dashboard/invoices'
    | '/dashboard/jobs'
    | '/dashboard/settings'
    | '/engineer/jobs'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/engineer'
    | '/login'
    | '/signup'
    | '/customer/jobs'
    | '/dashboard/customers'
    | '/dashboard/dispatch'
    | '/dashboard/engineers'
    | '/dashboard/invoices'
    | '/dashboard/jobs'
    | '/dashboard/settings'
    | '/engineer/jobs'
    | '/dashboard'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/dashboard'
    | '/engineer'
    | '/login'
    | '/signup'
    | '/customer/jobs'
    | '/dashboard/customers'
    | '/dashboard/dispatch'
    | '/dashboard/engineers'
    | '/dashboard/invoices'
    | '/dashboard/jobs'
    | '/dashboard/settings'
    | '/engineer/jobs'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  EngineerRoute: typeof EngineerRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/jobs': {
      id: '/customer/jobs'
      path: '/jobs'
      fullPath: '/customer/jobs'
      preLoaderRoute: typeof CustomerJobsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dispatch': {
      id: '/dashboard/dispatch'
      path: '/dispatch'
      fullPath: '/dashboard/dispatch'
      preLoaderRoute: typeof DashboardDispatchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/engineers': {
      id: '/dashboard/engineers'
      path: '/engineers'
      fullPath: '/dashboard/engineers'
      preLoaderRoute: typeof DashboardEngineersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/engineer/jobs': {
      id: '/engineer/jobs'
      path: '/jobs'
      fullPath: '/engineer/jobs'
      preLoaderRoute: typeof EngineerJobsRouteImport
      parentRoute: typeof EngineerRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomerRouteChildren {
  CustomerJobsRoute: typeof CustomerJobsRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerJobsRoute: CustomerJobsRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDispatchRoute: typeof DashboardDispatchRoute
  DashboardEngineersRoute: typeof DashboardEngineersRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDispatchRoute: DashboardDispatchRoute,
  DashboardEngineersRoute: DashboardEngineersRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EngineerRouteChildren {
  EngineerJobsRoute: typeof EngineerJobsRoute
}

const EngineerRouteChildren: EngineerRouteChildren = {
  EngineerJobsRoute: EngineerJobsRoute,
}

const EngineerRouteWithChildren = EngineerRoute._addFileChildren(
  EngineerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  EngineerRoute: EngineerRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
